#
# Makefile for the e-pack drivers
#

obj-$(CONFIG_INPUT_EPACK) += epack.o
obj-$(CONFIG_INPUT_EPACK) += epack_fw.o
#obj-$(CONFIG_INPUT_EPACK) += epack_aud.o
#obj-$(CONFIG_INPUT_EPACK) += epack_pwr.o
#obj-$(CONFIG_INPUT_EPACK) += epack_usb.o
