#
# Makefile for misc devices that really don't fit anywhere else.
#
# include $(srctree)/drivers/misc/mediatek/Makefile.custom
include $(srctree)/drivers/misc/mediatek/cam_cal/src/Makefile.custom

obj-y			+= Common_eeprom.o
