#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_LGSIC_LG4945)	+= touch_lg4945.o
obj-$(CONFIG_LGE_TOUCH_LGSIC_LG4945)	+= touch_lg4945_abt.o
obj-$(CONFIG_LGE_TOUCH_LGSIC_LG4945)	+= touch_lg4945_prd.o
obj-$(CONFIG_LGE_TOUCH_LGSIC_LG4945)	+= touch_lg4945_watch.o