ccflags-y += -I$(srctree)/drivers/misc/mediatek/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/bmi160-new
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
obj-y	:=  bmi160_gyro.o

