
# In case the platform does NOT support this type of sensors

obj-$(CONFIG_LEDS_RT4832) += rt4832/
obj-$(CONFIG_LEDS_DW8767) += dw8767/
obj-$(CONFIG_LEDS_LM3648) += lm3648/
obj-$(CONFIG_LEDS_RT4832_SF3) += rt4832_sf3/
obj-$(CONFIG_LEDS_RT4832_PH1) += rt4832_ph1/
obj-$(CONFIG_LEDS_RT4832_K6PNA) += rt4832_k6pna/
obj-$(CONFIG_LEDS_RT4832_LV5) += rt4832_lv5/
obj-$(CONFIG_LEDS_LM3632_LV5) += lm3632_lv5/
obj-$(CONFIG_LEDS_RT4832_CV1) += rt4832_cv1/
obj-$(CONFIG_LEDS_DW8767_CV1) += dw8767_cv1/
obj-$(CONFIG_LGE_DSV_SM5109) += sm5109/