#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/lge/

obj-$(CONFIG_LGE_TOUCH_LG4894)		+= touch_lg4894.o
obj-$(CONFIG_LGE_TOUCH_LG4894)		+= touch_lg4894_prd.o
obj-$(CONFIG_LGE_TOUCH_LG4894)		+= touch_lg4894_abt.o