ccflags-y += -Wno-error

ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach

obj-y	:=  bma4.o bma421.o bma4xy_driver.o

